Fix build errors
- Fix `package.json` to include missing dependencies
- Fix the error TS6133 by removing unused `React` import
- Update release workflow to handle .dmg file renaming